# Generated by Django 4.2 on 2023-09-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_post_content_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='state',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
