# Generated by Django 4.2 on 2023-09-08 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_usermodel_signupmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='mobile_no',
        ),
    ]
