# Generated by Django 4.2 on 2023-09-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_signupmodel_mobile_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_add_post', 'can_add_posts'), ('Can_delete_post', 'can_delete_posts'), ('Can_view_post', 'can_view_posts'), ('Can_change_category', 'can_chnage_posts')]},
        ),
    ]
