# Generated by Django 4.2 on 2023-09-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='categoryurl', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default='posturl', max_length=100),
        ),
    ]
