# Generated by Django 4.2 on 2023-09-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_category_url_alter_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default='Video', upload_to='video/%y'),
        ),
    ]
